account/urls.py
"""Account urls."""
from account import views
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

app_name = "account"
urlpatterns = [
    path('my_profile/edit/', views.Editsettings.as_view(), name="my_profile"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('activate/<str:confirmation_token>', views.ActivateUserView.as_view(), name="activate"),
    path('password/', views.change_password, name='change_password'),
    path('logout', views.logout, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name="account/login.html", redirect_authenticated_user=True),
         name='login'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html",
                                                        email_template_name='account/password_reset_email.html',
                                                        subject_template_name='account/password_reset_subject.txt',
                                                        success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",
                                                     success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
         name='password_reset_complete'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),
         name='password_reset_done'),
    path('my_profile/avatar/create/', views.AvatarCreateView.as_view(), name='my_profile_avatar_create'),
    path('my_profile/avatar/list', views.AvatarListView.as_view(), name='my_profile_avatar_list'),
    path('<int:pk>/my_profile/', views.ShowProfilePageView.as_view(), name="show_profile_page"),
    path('<int:pk>/edit_profile/', views.EditProfilePageView.as_view(), name="edit_profile_page"),
    path('create_profile/', views.CreateProfileView.as_view(), name="create_profile_page"),

]

api/urls.py
"""API urls."""

from api.views import BooksAPIViewSet, PostAPIViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(prefix='posts', viewset=PostAPIViewSet, basename='post')
router.register(prefix='books_view', viewset=BooksAPIViewSet, basename='book')

urlpatterns = router.urls

django_02/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(openapi.Info(
    title='Snippets Api',
    default_version='v1',
    description='Description',
    terms_of_service='http://www.google.com/policies/terms/',
    contact=openapi.Contact(email='contact@snippets.local'),
    license=openapi.License(name='BSD License'),

),
    public=True,
    permission_classes=(permissions.AllowAny,)
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('account.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    re_path(r'^api/v1/swagger/(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0),
            name='schema-json-no-ui'),
    re_path(r'^api/v1/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^api/v1/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-swagger-ui'),
]

main/urls.py
"""Project urls."""
# from django.contrib import admin
# from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include, path
from django.views.decorators import cache
from django.views.generic import TemplateView
from django_02 import settings

from . import views

urlpatterns = [
    # path('', views.index, name='homepage'),
    path('', TemplateView.as_view(template_name='main/index.html'), name='homepage'),
    # url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon/favicon.ico')),
    path('about/', views.about, name='about'),

    path('posts/create/', views.post_create, name='post_create'),
    path('posts/update/<int:post_id>/', views.post_update, name='post_update'),
    path('posts/<int:pk>/delete/', views.DeletePostView.as_view(), name='post_delete'),
    path('posts/', views.posts_all, name='posts_all'),
    path('posts/<int:post_id>/', views.post_show, name='post_show'),
    path('posts/list/', views.PostsListView.as_view(), name='post_list'),
    # path('posts/list/', cache.cache_page(120)(views.PostsListView.as_view()), name='post_list'),

    path('subcribers/new/', views.subscribers_new, name='subscribers_new'),
    path('subcribers/all/', views.subscribers_all, name='subscribers_all'),
    path('subscribers/email/', views.email_subscribers, name='email_subscribers'),

    path('authors/new/', views.authors_new, name='authors_new'),
    # path('authors/all/', views.authors_all, name='authors_all'),
    # path('authors/all/', cache.cache_page(120)(views.authors_all), name='authors_all'),
    path('authors/<int:pk>/delete/', views.DeleteAuthorsView.as_view(), name='author_delete'),
    path('authors/all/', views.AuthorsListView.as_view(), name='authors_all'),

    path('books/', views.books, name='books'),
    path('books/list/', views.BooksListView.as_view(), name='books_list'),
    # path('categories/', views.categories, name='categories'),
    path('categories/', cache.cache_page(120)(views.categories), name='categories'),

    path('contact-us/create/', views.ContactUsView.as_view(), name='contact-us-create'),

    path('posts/list/xlsx', views.DownloadPostsXLSX.as_view(), name='posts_xlsx'),

    path('api/posts/', views.api_posts, name='api_posts'),
    path('api/subcribe/', views.api_subscribe, name='api_subscribe'),
    path('api/authors/new/', views.api_authors_new, name='api_authors_new'),

    path('api/v1/', include('api.urls')),
    path('posts-page/', TemplateView.as_view(template_name='main/posts_page.html'), name='posts_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
"""Project forms."""
from django import forms
from django.forms import ModelForm, Select, Textarea, TextInput

from .models import Author, Comments, Post, Subscriber


class PostForm(ModelForm):
    """Post Form."""

    class Meta:
        """Form Meta."""

        model = Post
        fields = ['title', 'description', 'content']
        widgets = {
            "title": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Название статьи"
            }),
            "description": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Описание статьи"
            }),
            "content": Textarea(attrs={
                "class": "form-control",
                "placeholder": "Содержимое"
            })
        }

        def save(self, commit=True):
            """Manual save method for Subscriber."""
            print("Subscriber before save")
            # form.ModelForm.save(self,commit)
            sbr = super().save(commit=False)
            sbr.email_to = sbr.email_to.title()
            sbr.save()
            return sbr


class CommentsForm(ModelForm):
    """CommentsForm Class."""

    class Meta:
        """CommentsForm Meta."""

        model = Comments
        fields = ['body', 'subs_id']
        widgets = {
            "body": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Ваш комментариий"
            }

            ),
            "subs_id": Select(attrs={
                "class": "form-control",
                "placeholder": "подписчика ID"
            }),

        }


class SubscriberForm(ModelForm):
    """Subscriber Form."""

    author_id = forms.ModelChoiceField(
        queryset=Author.objects.all().order_by('name'),
        empty_label="Выберите автора",
        widget=forms.Select(
            attrs={"class": "form-control"}
        )
    )

    class Meta:
        """Subscriber Form Meta."""

        model = Subscriber
        fields = ['email_to', 'author_id']
        widgets = {
            "email_to": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Email подписчика "
            }
            ),
        }

main/views.py
"""Django Views."""
import io
from time import time

from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, View
from django_filters.views import FilterView
from faker import Faker
from main.filters import BooksFilter, PostFilter
from main.forms import PostForm, SubscriberForm
from main.models import Author, Book, Category, ContactUs, Post, Subscriber
from main.services.notify_service import notify
from main.services.post_service import comment_method, post_all, post_find
from main.services.subscribe_service import subscribe
from main.tasks import notify_subscriber_sync, notify_subscribers
import xlsxwriter


def index(request):
    """Route main page."""
    return render(request, "main/index.html")


def about(request):
    """Route About."""
    return render(request, "main/about.html", {"title": "About Company"})


def posts_all(request):
    """Route Posts."""
    context = {'title': "Posts", "posts": post_all()}
    return render(request, "main/posts_all.html", context)


def post_create(request):
    """Route Create Post."""
    errors = ''
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts_all")
        else:
            errors = "Не возможно сохранить пост."
    else:
        form = PostForm()
    context = {"form": form, "errors": errors}
    return render(request, "main/post_create.html", context=context)


def subscribers_new(request):
    """Route to Subscribe Author."""
    success = False
    email_to = request.POST.get('email_to')
    errors = ''
    if request.method == "POST":
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            success = True
        else:
            errors = form.errors
    else:
        form = SubscriberForm()

    if success:
        notify_subscriber_sync.delay(email_to)
        return redirect('subscribers_all')

    context = {"form": form, "errors": errors}
    return render(request, "main/subscribers_new.html", context=context)


def subscribe_notify(author_id, email_to):
    """Subscribe and Notify."""
    subscribe(author_id, email_to)
    notify(email_to)


def subscribers_all(request):
    """Route to All Subscribers."""
    all_subs = Subscriber.objects.all()
    return render(request, "main/subscribers_all.html", {"title": "Все подписки", "subscribers_all": all_subs})


def email_subscribers(request):
    """Route for Email All Subscribers."""
    start_time = time()
    notify_subscribers.delay()
    end_time = time() - start_time
    print(end_time)
    return redirect('homepage')


def authors_new(request):
    """Generate new Author."""
    fake = Faker()
    Author(name=fake.name(), email=fake.email()).save()
    return redirect("authors_all")


# def authors_all(request):
#     """Route to Authors List."""
#     all_authors = Author.objects.all().prefetch_related('books')
#     return render(request, "main/authors_all.html", {"title": "Авторы", "authors": all_authors})


def books(request):
    """Route to Books."""
    all_books = Book.objects.all().select_related('author', 'category')
    return render(request, 'main/books.html', {'title': 'Книги', 'books': all_books})


def categories(request):
    """Route to Categories."""
    all_categories = Category.objects.only('name').distinct().prefetch_related('books')
    return render(request, 'main/categories.html', {'title': 'Категории', 'categories': all_categories})


def post_update(request, post_id):
    """Update Posts."""
    err = ""
    pst = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(instance=pst, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts_all")
        else:
            err = "Не возможно обновить пост."
    else:
        form = PostForm(instance=pst)
    context = {
        "form": form,
        "err": err
    }
    return render(request, "main/post_update.html", context=context)


def post_show(request, post_id):
    """Route to Post by ID."""
    pst = post_find(post_id)
    comment_form, comments = comment_method(pst, request)
    return render(request, "main/post_show.html",
                  {"title": pst.title, "pst": pst, "comments": comments, "comment_form": comment_form})


def api_authors_new(request):
    """Route New Author API."""
    fake = Faker()
    Author(name=fake.name(), email=fake.email()).save()
    authors = Author.objects.all().values("name", "email")
    return JsonResponse(list(authors), safe=False)


def api_posts(request):
    """Route Posts API."""
    posts = post_all()
    responded = [dict(title=post.title, description=post.description, content=post.content) for post in posts]
    return JsonResponse(responded, safe=False)


def api_subscribe(request):
    """Route Subscribers API."""
    author_id = request.GET["author_id"]
    email_to = request.GET["email_to "]
    get_object_or_404(Author, pk=author_id)
    subscribe_notify(author_id, email_to)
    data = {"author_id": author_id}
    return JsonResponse(data, safe=False)


class PostsListView(FilterView):
    """Show list of posts analogously."""

    paginate_by = 10
    template_name = 'main/post_list.html'
    filterset_class = PostFilter

    def get_queryset(self):
        """Return posts queryset."""
        queryset = Post.objects.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        """Return posts context data."""
        context = super().get_context_data(*args, **kwargs)
        context["get_params"] = '&'.join(f"{key}={val}" for key, val in self.request.GET.items() if key != "page")
        context["cnt"] = context['object_list'].count()
        context["title"] = "All posts"
        return context


class ContactUsView(CreateView):
    """Create contact us Form as view."""

    success_url = reverse_lazy("homepage")
    model = ContactUs
    fields = ("email", "subject", "msg")


class DownloadPostsXLSX(View):
    """XLSX-Format Download."""

    def get(self, request):
        """Get method."""
        output = io.BytesIO()
        wb = xlsxwriter.Workbook(output)
        ws = wb.add_worksheet()
        all_p = Post.objects.all()
        counter = 0
        for p in all_p:
            counter = counter + 1
            ws.write(counter, 0, p.title)
        wb.close()
        output.seek(0)

        f_name = 'Posts.xlsx'
        response = HttpResponse(
            output,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=%s' % f_name

        return response


class AuthorsListView(ListView):
    """Show list of posts analogously."""

    def get_queryset(self):
        """Set queryset to listview."""
        key = Author().__class__.cache_key()
        if key in cache:
            queryset = cache.get(key)
        else:
            queryset = Author.objects.all().prefetch_related("books")
            cache.set(key, queryset, 60)
        return queryset


class AuthorsListView2(ListView):
    """Show list of posts ."""

    model = Author
    template_name = 'main/author_list_js.html'


class DeletePostView(DeleteView):
    """Delete posts."""

    model = Post
    template_name = "main/post_delete.html"
    success_url = reverse_lazy("post_list")


class DeleteAuthorsView(DeleteView):
    """Delete Authors."""

    model = Author
    template_name = "main/author_delete.html"
    success_url = reverse_lazy("authors_all")


class BooksListView(FilterView):
    """Show list of books analogously."""

    paginate_by = 10
    template_name = 'main/books_filter.html'
    filterset_class = BooksFilter

    def get_queryset(self):
        """Return books queryset."""
        queryset = Book.objects.all().only("title", "category").select_related("category")
        return queryset

    def get_context_data(self, *args, **kwargs):
        """Return books context data."""
        context = super().get_context_data(*args, **kwargs)
        context["get_params"] = '&'.join(f"{key}={val}" for key, val in self.request.GET.items() if key != "page")
        context["cnt"] = context['object_list'].count()
        context["title"] = "All books"
        return context

main/templates/main/author_delete.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}

    <div class="select2-container"></div>
        <h1>Удалить автора</h1>
    <h3>Удаление автора {{ author.name }}</h3>
        <div class="payload">
            <form method="post">
                {% csrf_token %}
                <strong>Удалить автора?</strong>
                <br>
                <br>
                <button class="btn btn-danger">Удалить</button>
            </form>
        </div>

{% endblock %} 

main/templates/main/author_list.html
{% extends "main/base.html" %}

{% block title %}Автора{% endblock %}
{% block  content %}
    <div class="container"></div>
    <h1>Авторы</h1>
    <div class="payload">
        <table class="table table-hover">

            <thead>
            <tr>
                <th scope="col"><span style="color: black; ">ID</span></th>
                <th scope="col"><span style="color: black; ">Имя</span></th>
                <th scope="col"><span style="color: black; ">Почта</span></th>
                <th scope="col"><span style="color: black; ">Количество книг</span></th>
            </tr>
            </thead>
            <tbody>
            {% for author in author_list %}
                <tr>
                    <th scope="row"><span style="color: #727272; ">{{ author.id }}</span></th>
                    <th scope="row"><span style="color: #727272; ">{{ author.name }} {{ author.surname }}</span></th>
                    <th scope="row"><span style="color: #727272; ">{{ author.email }}</span></th>
                    <th scope="row"><span style="color: #727272; ">{{ author.books.count }}</span></th>
                    {% if request.user.is_authenticated %}
                        <th scope="row"><span><a href="{% url "author_delete" author.id %}">(Delete)</a></span></th>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %} 

main/templates/main/base.html
<!doctype html>
<html lang=" ">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/styles/main.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="nav justify-content-between bg-primary">
    <a class="p-3 text-white link-secondary" href="{% url "homepage" %}">Домашняя</a>
    <a class="p-3 text-white link-secondary" href="{% url "about" %}">Про сайт</a>
    <a class="p-3 text-white link-secondary" href="{% url "post_list" %}">Список постов</a>
{#    <a class="p-3 text-white link-secondary" href="{% url "posts_all" %}">Посты</a>#}
{#    <a class="p-3 text-white link-secondary" href="{% url "post_create" %}">Создать Пост</a>#}
{#    <a class="p-3 text-white link-secondary" href="{% url "subscribers_new" %}">Подписаться на автора</a>#}
{#    <a class="p-3 text-white link-secondary" href="{% url "authors_new" %}">Сгенерировать автора</a>#}
    <a class="p-3 text-white link-secondary" href="{% url "authors_all" %}">Все авторы</a>
{#    <a class="p-3 text-white link-secondary" href="{% url "email_subscribers" %}">Оповестить подписчиков</a>#}
{#    <a class="p-3 text-white link-secondary" href="{% url "api_posts" %}">API</a>#}
{#    <a href="{% url "books" %}" class="p-3 text-white link-secondary">Книги</a>#}
    <a href="{% url "categories" %}" class="p-3 text-white link-secondary">Категории</a>
    <a class="p-3 text-white link-secondary" href="{% url "posts_xlsx" %}">Скачать Посты</a>
    {% if request.user.is_authenticated %}
        {% if user.profile.id %}
            <a class="p-3 text-white link-secondary" href="{% url "account:show_profile_page" request.user.id %}">Мой Аккаунт</a >
            <a class="p-3 text-white link-secondary" href="{% url "account:edit_profile_page" request.user.id %}">Изменить профиль</a>
        {% else %}
            <a class="p-3 text-white link-secondary" href="{% url "account:create_profile_page" %}">Создать профиль</a>
        {% endif %}
        <a class="p-3 text-white link-secondary" href="{% url "account:my_profile" %}">Настройки</a>
        <a class="p-3 text-white link-secondary" href="{% url "account:change_password" %}">Сменить пароль</a>
        <a class="p-3 text-white link-secondary" href="{% url "account:password_reset" %}">Восстановить пароль</a>
        <a class="p-3 text-white link-secondary" href="{% url "account:my_profile_avatar_create" %}">Загрузить аватар</a>
        <a class="p-3 text-white link-secondary" href="{% url "account:my_profile_avatar_list" %}">Все Аватарки</a>
        <a class="p-3 text-white link-secondary" href="{% url "account:logout" %}">Выход</a>
    {% else %}
        <a class="p-3 text-white link-secondary" href="{% url "account:login" %}">Вход</a>
        <a class="p-3 text-white link-secondary" href="{% url "account:signup" %}">Регистрация</a>
    {% endif %}
</nav>
<div class="content">
    {% block content %}{% endblock %}
</div>

<div class="footer-grey">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h4>Contact us</h4>
                    <ul>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact-us-create' %}">Send message</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h4>About</h4>
                    <ul>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h4>Blog</h4>
                    <p>Info about blog</p>
                </div>
            </div>
            <p class="copyright">Copyrights © 2021</p>
        </div>


    </footer>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
<script src="{%  static "js/author-list.js" %}"></script>
<script src="{%  static "js/posts-page.js" %}"></script>
</body>
</html>

main/templates/main/books.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block  content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <div class="payload">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col"><span style="color: black; ">ID</span></th>
                    <th scope="col"><span style="color: black; ">Книга</span></th>
                    <th scope="col"><span style="color: black; ">Автор</span></th>
                    <th scope="col"><span style="color: black; ">Категория</span></th>
                </tr>
                </thead>
                <tbody>
                {% for book in books %}
                <tr>
                    <th scope="row"><span style="color: #727272; ">{{ book.id }}</span></th>
                    <th scope="row"><span style="color: #727272; ">{{ book.title }}</span></th>
                    <th scope="row"><span style="color: #727272; ">{{ book.author }}</span></th>
                    <th scope="row"><span style="color: #727272; ">{{ book.category }}</span></th>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

main/templates/main/books_filter.html
{% extends 'main/base.html' %}

{% block title %}
All books
{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <div class="payload">
                    <div class="mb-1">Count: {{ cnt }}</div>
            <form method="GET">
                {{ filter.form.as_p }}
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search"></span>Search
                </button>
            </form>
            <br>
            <hr>
        <table class="table table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Book ID</th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
            </tr>
            </thead>
            <tbody>
            {% for book in books_list %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.category.name}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
            <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    {% if is_paginated %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ get_params }}">&laquo;</a></li>
                            {% else %}
                                <li class="page-item active">
                                     <span class="sr-only">&laquo;</span></a>
                                    </li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link" href={{ i }}>{{ i }}<span class="sr-only">(current)</span></a>
                                    </li>
                                {% else %}
                                    <li><a class="page-link" href="?page={{ i }}{{ get_params }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ get_params }}">&raquo;</a></li>
                            {% else %}
                                <li class="page-item active">
                                     <span class="sr-only">&raquo;</span></a>
                                    </li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %}Main Page{% endblock %}
{% block  content %}
    <h1>Main Page</h1>
    <h4>Вы на домашней странице!</h4>
    <div class="container main-content"></div>
{% endblock %}

main/templates/main/post_delete.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}
    <div class="select2-container"></div>
        <h1>Удалить пост</h1>
    <h3>Удаление поста {{ post.title }}</h3>
        <div class="payload">
            <form method="post">
                {% csrf_token %}
                <strong>Удалить пост?</strong>
                <br>
                <br>
                <button class="btn btn-danger">Удалить</button>
            </form>
        </div>

{% endblock %} 

main/templates/main/post_list.html
{% extends 'main/base.html' %}

{% block title %}Posts{% endblock %}


{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <div class="payload">
        <ul>
            {% for post in post_list %}
            <h4>
                <a href="{% url 'post_show' post_id=post.id %}">{{ post.title }}</a>
            </h4>
            <li class="row">
                <span class="grey summary">{{ post.description }}</span>
                {{ post.content }}
            </li>
            <hr>

            {% endfor %}
        </ul>
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ get_params }}">&laquo;</a></li>
                        {% else %}
                            <li class="page-item active">
                                 <span class="sr-only">&laquo;</span>
                            </li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <a class="page-link" href={{ i }}>{{ i }}<span class="sr-only">(current)</span></a>
                                </li>
                            {% else %}
                                <li><a class="page-link" href="?page={{ i }}{{ get_params }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ get_params }}">&raquo;</a></li>
                        {% else %}
                            <li class="page-item active">
                                 <span class="sr-only">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

main/templates/main/posts_page.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block  content %}

    <div id="app"></div>

{% endblock %}